- hosts: all
  roles:
  - Stouts.nginx
  - Stouts.python
  tasks:
    - import_tasks: tasks/main.yml
  handlers:
    - import_tasks: handlers/main.yml
  vars_files:
    - defaults/main.yml
    - tests/vars.yml
