#!/bin/sh

# This file was generated by Ansible for {{ansible_fqdn}}
# Do NOT modify this file by hand!

{% set app = item -%}
{% set virtualenv = item.get('virtualenv', wsgi_virtualenv) -%}
{% set pip = (virtualenv + '/bin/pip') if virtualenv else 'pip' -%}
{% set pip_packages = item.get('pip_packages', wsgi_pip_packages) -%}
{% set pip_requirements = item.get('pip_requirements') -%}

cd {{app.app_dir|default(wsgi_app_dir)}}

{% if virtualenv -%}
[ -d {{virtualenv}} ] || virtualenv {{virtualenv}} -p {{app.get('virtualenv_python', wsgi_virtualenv_python)}}
{% endif %}

{{pip}} install uWSGI

{% if pip_packages %}
{{pip}} install {{pip_packages}}
{% endif %}

{% if pip_requirements %}
{{pip}} install -r {{pip_requirements}}
{% endif %}
