#!/bin/sh

# This file was generated by Ansible for {{ansible_fqdn}}
# Do NOT modify this file by hand!

{% set app = item -%}
{% set virtualenv = app.get('virtualenv', wsgi_virtualenv) -%}
{% set pip = (virtualenv + '/bin/pip') if virtualenv else 'pip' -%}

cd {{app.app_dir|default(wsgi_app_dir)}}

{% if virtualenv -%}
[ -d {{virtualenv}} ] || virtualenv {{virtualenv}} -p {{app.get('virtualenv_python', wsgi_virtualenv_python)}}
{% endif %}

{{pip}} install uWSGI

{% if app.pip_packages|default(wsgi_pip_packages)  -%}
{{pip}} install {{app.pip_packages|default(wsgi_pip_packages)|join(' ')}}
{% endif %}

{% if app.get('pip_requirements') -%}
{{pip}} install -r {{app.get('pip_requirements')}}
{% endif %}
